### ISSUE TITLE
Broken implementation of mapping interface?

### ISSUE THREAD

**Issue by attilaolah** [conestack/node#3]
When I base my class on a `FactoryNode` and try to verify the implementation, I get this error message:
    BrokenMethodImplementation: The implementation of pop violates its contract
            because implementation doesn't support variable arguments.

Any idea why is this?

**Comment by rnixx** [comment]
@attilaolah Hi, i guess this issue is long outdated. I close it. If you think otherwise, please reopen ;)

**Comment by attilaolah** [comment]
Hahaha, yes there's no chance we can still repro this :)
